version: '3.8'

services:
  puppeteer-api:
    build: .
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    restart: unless-stopped
    mem_limit: 512m
    mem_reservation: 256m
    cpus: '0.5'
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s